# Generated by Django 3.1 on 2021-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(choices=[('Sport', 'sport'), ('Movies', 'movies'), ('Books', 'books'), ('Programming', 'prog')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
